#!/bin/bash

# This script acts as a front end for cardano-node. If it finds an actual cardano-node binary
# outside this directory in the PATH, it will invoke that binary with the supplied arguments.
# If it doesn't find a cardano-node binary, it will run cardano-node in a docker container,
# mounting the appropriate volumes and setting the proper environment variables.
#
# Note: this is for one-off invocations (version, key/cert utilities). The long-running
# block-producing node is started by start-cardano-devnet via the cardano-node compose service.

unset nodepath
for i in $(echo "$PATH" | sed 's/:/ /g'); do
  if [[ $i != ${DEVNET_ROOT}* ]]; then
    if [ -x $i/cardano-node ]; then
      nodepath=$i
      break
    fi
  fi
done

newargs=()
for i in "${@:1}"; do
  tmp=$i
  if [[ $i == ${DEVNET_ROOT}* ]]; then
    tmp=("${i#$DEVNET_ROOT}")
  fi
  if [[ $i == ${CARDANO_CLI_GURU}* ]]; then
    tmp=("${i#$CARDANO_CLI_GURU}")
  fi
  newargs+=("${tmp}")
done

if [ -z ${nodepath+x} ]; then
  # cardano-node not in PATH external to this directory. Run via the cardano-cli service,
  # which shares the image and volume mounts, rather than the long-running cardano-node
  # service (that one has a fixed container_name and a block-producer command).
  exec docker compose -f $DEVNET_ROOT/docker-compose.yml run --rm -T \
    --entrypoint /usr/local/bin/cardano-node cardano-cli "${newargs[@]}"
else
  exec $nodepath/cardano-node "${@:1}"
fi
